"""описание изменений

Revision ID: e758b43b1e2f
Revises: 6d56b4feea45
Create Date: 2024-11-03 15:49:28.142948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e758b43b1e2f'
down_revision: Union[str, None] = '6d56b4feea45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('creater', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'creater')
    # ### end Alembic commands ###
